-- 通知テーブルの作成
CREATE TABLE notifications (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id UUID REFERENCES auth.users(id) ON DELETE CASCADE,
  actor_id UUID REFERENCES auth.users(id) ON DELETE CASCADE,
  type TEXT NOT NULL CHECK (type IN ('like', 'comment', 'achievement', 'milestone')),
  goal_id BIGINT REFERENCES goals(id) ON DELETE CASCADE,
  content TEXT NOT NULL,
  is_read BOOLEAN DEFAULT FALSE,
  created_at TIMESTAMPTZ DEFAULT NOW(),
  updated_at TIMESTAMPTZ DEFAULT NOW()
);

-- インデックスの作成
CREATE INDEX notifications_user_id_idx ON notifications(user_id);
CREATE INDEX notifications_created_at_idx ON notifications(created_at);

-- RLSポリシーの設定
ALTER TABLE notifications ENABLE ROW LEVEL SECURITY;

-- 既存のポリシーを削除（もし存在する場合）
DROP POLICY IF EXISTS "ユーザーは自分の通知のみ閲覧可能" ON notifications;
DROP POLICY IF EXISTS "通知の作成を許可" ON notifications;

-- 閲覧ポリシー
CREATE POLICY "ユーザーは自分の通知のみ閲覧可能"
  ON notifications FOR SELECT
  USING (auth.uid() = user_id);

-- 作成ポリシー
CREATE POLICY "通知の作成を許可"
  ON notifications FOR INSERT
  WITH CHECK (true);

-- 通知を作成するファンクション
CREATE OR REPLACE FUNCTION create_notification()
RETURNS TRIGGER AS $$
BEGIN
  -- いいねの通知
  IF TG_TABLE_NAME = 'goal_likes' THEN
    INSERT INTO notifications (user_id, actor_id, type, goal_id, content)
    SELECT 
      goals.user_id,
      NEW.user_id,
      'like',
      NEW.goal_id,
      CASE 
        WHEN NEW.clap_number = 10 THEN '目標に最大の応援をもらいました！'
        ELSE '目標に応援をもらいました'
      END
    FROM goals
    WHERE id = NEW.goal_id AND goals.user_id != NEW.user_id;
  
  -- コメントの通知
  ELSIF TG_TABLE_NAME = 'goal_comments' THEN
    INSERT INTO notifications (user_id, actor_id, type, goal_id, content)
    SELECT 
      goals.user_id,
      NEW.user_id,
      'comment',
      NEW.goal_id,
      CASE NEW.type
        WHEN 'support' THEN '目標に応援メッセージが届きました'
        WHEN 'experience' THEN '目標に経験シェアが届きました'
        WHEN 'advice' THEN '目標にアドバイスが届きました'
      END
    FROM goals
    WHERE id = NEW.goal_id AND goals.user_id != NEW.user_id;
  END IF;

  RETURN NEW;
END;
$$ LANGUAGE plpgsql;

-- トリガーの作成
CREATE TRIGGER create_like_notification
  AFTER INSERT ON goal_likes
  FOR EACH ROW
  EXECUTE FUNCTION create_notification();

CREATE TRIGGER create_comment_notification
  AFTER INSERT ON goal_comments
  FOR EACH ROW
  EXECUTE FUNCTION create_notification(); 