-- 新しいカラムを追加
alter table goals
add column if not exists likes_count bigint default 0,
add column if not exists liked_by_me boolean default false;

-- いいねをカウントするトリガー関数
create or replace function update_goal_likes_count()
returns trigger
language plpgsql
security definer
as $$
begin
  if (TG_OP = 'INSERT') then
    update goals
    set likes_count = likes_count + 1
    where id = NEW.goal_id;
  elsif (TG_OP = 'DELETE') then
    update goals
    set likes_count = likes_count - 1
    where id = OLD.goal_id;
  end if;
  return null;
end;
$$;

-- いいねトリガーを設定
drop trigger if exists goal_likes_count_trigger on goal_likes;
create trigger goal_likes_count_trigger
after insert or delete on goal_likes
for each row
execute function update_goal_likes_count();

-- いいね状態を更新する関数
create or replace function update_goal_liked_by_me(p_goal_id bigint, p_user_id uuid)
returns void
language plpgsql
security definer
as $$
begin
  update goals
  set liked_by_me = exists(
    select 1
    from goal_likes
    where goal_id = p_goal_id
    and user_id = p_user_id
  )
  where id = p_goal_id;
end;
$$;

-- いいね状態を更新するトリガー関数
create or replace function update_goal_liked_by_me_trigger()
returns trigger
language plpgsql
security definer
as $$
begin
  if (TG_OP = 'INSERT') then
    perform update_goal_liked_by_me(NEW.goal_id, NEW.user_id);
  elsif (TG_OP = 'DELETE') then
    perform update_goal_liked_by_me(OLD.goal_id, OLD.user_id);
  end if;
  return null;
end;
$$;

-- いいね状態トリガーを設定
drop trigger if exists goal_liked_by_me_trigger on goal_likes;
create trigger goal_liked_by_me_trigger
after insert or delete on goal_likes
for each row
execute function update_goal_liked_by_me_trigger();

-- 既存のデータをバックアップ
CREATE TEMP TABLE goal_likes_backup AS SELECT * FROM goal_likes;

-- 既存のテーブルを削除
DROP TABLE goal_likes;

-- goal_likesテーブルを再作成
CREATE TABLE goal_likes (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  goal_id BIGINT REFERENCES goals(id) ON DELETE CASCADE,
  user_id UUID REFERENCES auth.users(id) ON DELETE CASCADE,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL,
  clap_number INTEGER NOT NULL DEFAULT 1,
  CONSTRAINT goal_likes_goal_id_user_id_clap_number_key UNIQUE (goal_id, user_id, clap_number)
);

-- バックアップからデータを復元
INSERT INTO goal_likes (goal_id, user_id, created_at, clap_number)
SELECT goal_id, user_id, created_at, 1 as clap_number
FROM goal_likes_backup;

-- 一時テーブルを削除
DROP TABLE goal_likes_backup;

-- RLSポリシーの設定
ALTER TABLE goal_likes ENABLE ROW LEVEL SECURITY;

-- 既存のポリシーを削除
DROP POLICY IF EXISTS "Anyone can view goal likes" ON goal_likes;
DROP POLICY IF EXISTS "Authenticated users can create likes" ON goal_likes;
DROP POLICY IF EXISTS "Users can delete their own likes" ON goal_likes;

-- ポリシーを作成
CREATE POLICY "Anyone can view goal likes" 
  ON goal_likes FOR SELECT 
  USING (true);

CREATE POLICY "Authenticated users can create likes"
  ON goal_likes FOR INSERT
  WITH CHECK (auth.uid() = user_id);

CREATE POLICY "Users can delete their own likes"
  ON goal_likes FOR DELETE
  USING (auth.uid() = user_id);

-- インデックスの追加
CREATE INDEX goal_likes_goal_id_user_id_clap_number_idx 
ON goal_likes (goal_id, user_id, clap_number); 